services:
  api-gateway:
    build:
      context: ./API_Gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    develop:
      watch:
        - path: ./API_Gateway/
          target: /app/
          action: sync
        - path: ./API_Gateway/package.json
          action: rebuild
    env_file:
      - ./API_Gateway/.env
    depends_on:
      auth:
        condition: service_healthy
      product:
        condition: service_healthy
    ports:
      - "8080:8080"
  auth:
    build:
      context: ./Auth
      dockerfile: Dockerfile
    container_name: auth
    develop:
      watch:
        - path: ./Auth/
          target: /app/
          action: sync
        - path: ./Auth/package.json
          action: rebuild
    env_file:
      - ./Auth/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - authDb
  product:
    build:
      context: ./Products
      dockerfile: Dockerfile
    container_name: product
    develop:
      watch:
        - path: ./Products/
          target: /app/
          action: sync
        - path: ./Products/package.json
          action: rebuild
    env_file:
      - ./Products/.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - productDb

  authDb:
    image: mongo:latest
    container_name: authDb
    volumes:
      - db_data_auth:/data/db
    ports:
      - "27018:27017"
  productDb:
    image: mongo:latest
    container_name: productDb
    volumes:
      - db_data_product:/data/db
    ports:
      - "27019:27017"
volumes:
  db_data_auth:
  db_data_product:
